require 'plugins'
require 'options'
require 'mappings'
require 'configs.lsp'
require 'configs.telescope'
require 'configs.treesitter'
require 'configs.undotree'
require 'configs.harpoon'
require 'configs.fugitive'
require 'configs.dadbod'

